### ISSUE TITLE
Windows 10 Defender: Trojan:Win32/Cloxer.D!cl

### ISSUE THREAD

**Issue by jnovack** [edipo2s/LotusTracker#65]
![image](https://user-images.githubusercontent.com/387006/50565692-61e37080-0cff-11e9-9d76-86503f53748e.png)

**Comment by edipo2s** [comment]
Hey Jnovack, As VirusTotal confirm, there's no Trojan on Lotus Tracker, Windows Defender warning is just a false positive. The lack of digital signature open door for this kind if things.
