### ISSUE TITLE
Fix for MTGA client notification bug

### ISSUE THREAD

**Issue by maturz** [edipo2s/LotusTracker#68]
When there is a reveal screen (e.g. when you are playing Nexus of Fate) there is a bug in MTGA client and you don't get a notification/[blinking of the client window](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-flashwindowex) if you are tabbed out of the game. If this is visible in the log maybe it would be an easy thing to implement a workaround in LotusTracker?

**Comment by edipo2s** [comment]
Hi Maturz,

Lotus Tracker can't interact with MTGA client, so it's better wait for they fix this.
