### ISSUE TITLE
No overlay after attempting to increase size

### ISSUE THREAD

**Issue by crafty35a** [edipo2s/LotusTracker#73]
When I hit the plus sign to increase the size of my deck list overlay, it just disappeared -- and now I can't get it to reappear. Interestingly, I can increase the size of the opponent's overlay without issue. I am using the Windows version of LotusTracker.

**Comment by crafty35a** [comment]
Interestingly, I can increase the size of the opponent's overlay without issue.

**Comment by crafty35a** [comment]
Scaling seems to be working now after resetting to default settings -- I will close the issue and let you know if it happens again.

**Comment by edipo2s** [comment]
I see, the overlay also sometime disappear with me because some issue with touchpad that seems to just throw it away from screen. So reset bring it back to original position.
