### ISSUE TITLE
Chance of opening 5th is incorrect

### ISSUE THREAD

**Issue by AnnanFay** [edipo2s/LotusTracker#74]
In Dominaria I have 5 full rare playsets and 1 mythic playset. 6 / (17+56) = 8.2% chance of opening a 5th copy.

![image](https://user-images.githubusercontent.com/766048/50929169-80aadb00-1454-11e9-8f7e-ccee1fe234a1.png)
![image](https://user-images.githubusercontent.com/766048/50929178-86082580-1454-11e9-9644-0aface019d4d.png)

**Comment by edipo2s** [comment]
Fixed!
