### ISSUE TITLE
MTG Arena Pro: "Lotus Tracker detected! Tracking is blocked by that software."

### ISSUE THREAD

**Issue by AnnanFay** [edipo2s/LotusTracker#83]
It's not clear if @Razviar has been in contact to report this issue directly. If not then it is important someone does. The current version of [MTG Arena Pro](https://github.com/Razviar/mtga-pro-tracker) has this message when you start it at the same time as Lotus Tracker.

![image](https://user-images.githubusercontent.com/766048/52373258-1df82f80-2a52-11e9-9f5a-59de804723a7.png)

The message reads: "Lotus Tracker detected! Tracking is blocked by that software."

On Reddit the developer [has said](https://old.reddit.com/r/MTGArenaPro/comments/am0d6o/lotus_tracker_detected/):

> This is simple: Lotus Tracker blocks log file from being correctly parsed by our software, because it reads log on crazy frequency every 250 ms. And we are receiving some complaints from users like "my matches are getting lost". So this is precaution. Pay attention: all other trackers are behaving more polite regarding log parsing, so we have no problems with them. You can easily use MTGA Pro Tracker with MTGA Tracker or MTGA Tools. But not Lotus.

> We have overlay and draft helper now, covering basically all necessary functions, so, in fact, users do have to choose eventually.

Me and /u/brittspace asked in the above thread if Lotus Tracker had been made aware of the issue but Razviar has yet to reply as of this post.

As far as I know neither Arena Tool nor MTGA Tracker have issues with how Lotus Tracker parses the logs. I don't claim to know who is at fault, but whatever the issue is I think it should be fixed so both trackers can run at the same time.

**Comment by edipo2s** [comment]
As user ainyru said on thread, its impossible to block log just by reading it with any frequency. And Lotus don't open log file exclusive mode, if it does, others trackers would not works together too. This is cleary a marketing move to forcing users to user his new overlay and draft features by blocking the best alternative option in this point. Is really a shame that the developer do that, and you can't ever see the code to check if would be any chance of a real problem exists.

**Comment by malchmih** [comment]
@edipo2s I don't really know is there a problem for MTG Arena Pro, but the issue exists. I can not, for instance, create a zip archive from log file when Lotus is running. Currently I am stopping Lotus tracker, creating archive and then relaunching the tracker. MTG Arena may not be even running. You can try it yourself

**Comment by edipo2s** [comment]
I didn't have problems with MTG Arena running, but I will analyse the create zip archive test @malchmih , thanks

**Comment by edipo2s** [comment]
@malchmih Lotus Tracker opens the log file to read when it detect some window with "MGTA" title, and close the file when it don't find anyone more. The problem in this case, is that when you open the log folder, which is named "MTGA", Lotus interpret that like MGTA Arena has start to running, so it open the log file to read and this may block create a zip archive @malchmih 

I'll try improve that.

**Comment by malchmih** [comment]
Thank you! Not taking any "side" here, but could this be the same issue as the mentioned above (with MTGA Pro tracker)? I'd be better for all the tracker to coexist now if possible since they all offer something different now. I personally love Lotus's layout - it is the most clean one, but use MTGA Pro site for collection tracking, deck creation etc. (I'm also using https://mtgahelper-app.azurewebsites.net/ and MTG Arena Tool)

**Comment by edipo2s** [comment]
I see. The MTG Arena pro developer said that the problem was that Lotus is reading the log file at high frequency. I don't understand this at a problem, but anyway, I can reduce the frequency if it would solve the problems. I ever asked it in mentioned thread above, what frequency it uses. Waiting for response.

**Comment by Zeromark30** [comment]
just rename the lotus exe and they work together fine

**Comment by edipo2s** [comment]
Very good to know that Zeromark30, more one prove that there's nothing wrong, it's just a poor decision from MTG Arena pro against its competitor.
Thanks
